### ISSUE TITLE
Failed to import reboot from pychromecast.dial

### ISSUE THREAD

**Issue by Onion2222** [muammar/mkchromecast#366]
Command:
```
arthur@arthur-laptop:~$ sudo mkchromecast --video --screencast 
Traceback (most recent call last):
  File "/usr/bin/mkchromecast", line 8, in <module>
    from mkchromecast.cast import *
  File "/usr/share/mkchromecast/mkchromecast/cast.py", line 14, in <module>
    from pychromecast.dial import reboot
ImportError: cannot import name 'reboot' from 'pychromecast.dial' (/usr/local/lib/python3.8/dist-packages/pychromecast/dial.py)
arthur@arthur-laptop:~$ 
```

When I'm executing this command, i get an error about pychromcast.dial.

About pychomecast:
```
arthur@arthur-laptop:~$ pip3 show pychromecast
Name: PyChromecast
Version: 9.2.0
Summary: Python module to talk to Google Chromecast.
Home-page: https://github.com/balloob/pychromecast
Author: Paulus Schoutsen
Author-email: paulus@paulusschoutsen.nl
License: MIT
Location: /home/arthur/.local/lib/python3.8/site-packages
Requires: protobuf, casttube, zeroconf
Required-by: 
```

I'm not an expert at Python, so I can't dig deeper...

**Comment by Onion2222** [comment]
Solved by executing: `sudo pip3 install pychromecast==4.1.1`

**Comment by c3m0** [comment]
I have the same issue, and pip3 install .. did not resolve it! :/
Running Raspian (Rapsberry)
