### ISSUE TITLE
Cannot connect to a single Chromecast Audio

### ISSUE THREAD

**Issue by sabret00the** [muammar/mkchromecast#50]
I have two on my network and whenever trying to connect to one, both connect.

**Comment by muammar** [comment]
Are you in Linux or macOS?. This problem was reported in #41 and it is solved in latest versions of mkchromecast. If you are on macOS, I am afraid that I am not able to provide a standalone app (see #36). If it is your case, you will have to use the application from console or [compile the app following these instructions](https://github.com/muammar/mkchromecast/wiki/macOS-standalone-app).

**Comment by sabret00the** [comment]
I'm on Linux. I'll try updating and see if that works.

**Comment by muammar** [comment]
> I'm on Linux. I'll try updating and see if that works.

Any update on this?. Can this report be closed?.

**Comment by pasikarkkainen** [comment]
This is still broken, happens also on OSX.

**Comment by sabret00the** [comment]
Confirming that this is still broken.

**Comment by muammar** [comment]
I have at home Chromecast and Chromecast Audio. When I pushed this to try solve the issue, I could select one of the two. I will try again to see if I get the same problem as you have described.

**Comment by pasikarkkainen** [comment]
Oh, I forgot to mention.. my comment above applies to version 0.3.6.

**Comment by sabret00the** [comment]
It's probably important to note that I have a Chromecast and two Chromecast audios. I also have a group set up with just the Chromecast audios and whenever I try and send audio to my Kitchen Chromecast, both the Kitchen and Bathroom are selected in the mkchromecast dropdown with mkchromecast always seemingly preferring the Bathroom Chromecast.

**Comment by muammar** [comment]
@pasikarkkainen that is a known problem with 0.3.6. You may try 0.3.7. 

@sabret00the Are you using 0.3.6, too?.

**Comment by sabret00the** [comment]
Yup, I too am using 0.3.6

**Comment by muammar** [comment]
You have to install 0.3.7 because the problem is fixed in that version. If you are using debian based distro, Ubuntu synced already 0.3.7 in their repo. For the case of macOS, I am afraid that you will have to use the application from sources as described in the README.

**Comment by sabret00the** [comment]
0.3.7 isn't linked from the releases on github and in order to get it from the Ubuntu repositories we apparently need to upgrade to the alpha status Ubuntu 17.04

**Comment by pasikarkkainen** [comment]
Ok, upgraded to v0.3.7 on Mac OSX (10.11.6 El Capitan), installed with brew, and still seeing this problem. pychromecast is version 0.7.7, if that matters. Here's more detailed analysis of the issue.. it's a bit long, but the issue isn't exactly straight forward to explain:

When you start the mkchromecast app and search for chromecast devices it seems sometimes they are found in different order.. it's quite random, but let's say that out of 15 times you start the mkchromecast app and search for devices, twice the devices are found on different order.. so most of the times they are found on same order, but not always. Ok, let's continue. As an example here you have the found devices:

- First device: Chromecast Audio.
- Second device: Chromecast Ultra.

- After searching If I click the first device to select it, *both* get selected. This happens every time. Clearly a bug.
- After searching If I click the second device to select it, only the second device gets selected. Selecting the second device seems to work every time like it should.

- When both devices are selected (due to the bug above), you *can* actually remove the selection from the first device by clicking on it, and this works as it should, leaving only the second device selected/working.
- When both devices are selected (due to the bug above), If you try to remove the selection from the second device by clicking on the second device, nothing happens, and both stay selected. Clearly a bug.

The end result: You can properly use only the device which is found as *second* on the list. If the device you *wanted* to use wasn't actually found as second device one has to restart and rescan many many times to make it happen.. Does that help finding and fixing the bug?

**Comment by sabret00the** [comment]
Tested this. I can confirm.

**Comment by muammar** [comment]
>Ok, upgraded to v0.3.7 on Mac OSX (10.11.6 El Capitan), installed with brew, and still seeing this problem. pychromecast is version 0.7.7, and QT is 5.8.0, if that matters. Here's more detailed analysis of the issue.. it's a bit long, but the issue isn't exactly straight forward to explain:

In brew, the version is 0.3.6:

https://github.com/caskroom/homebrew-cask/blob/master/Casks/mkchromecast.rb

When you reported **installed with brew**, are you referring to `brew cask install mkchromecast`.

I will check this again today. At home I have an audio chromecast and a regular one. I am able to connect to each of them separately when both online. I think https://github.com/muammar/mkchromecast/commit/12055e526c9783dce492b5d0313185efe545230e fixes the problem. In that commit, when one selects a CC, it is connected by using its name. Are the names different in your cases @pasikarkkainen  and @sabret00the?. But if you are still using something  lower than `0.3.7` this won't work. Can you report the Mkchromecast versions, please?. Use this command if using deb package `mkchromecast -v` or `python mkchromecast.py -v` if using from sources.

**Comment by sabret00the** [comment]
I'm definitely using 0.3.7 according to Terminal on Ubuntu.

Also one of mine is called Kitchen Chromecast while the other is called Bathroom Chromecast.

**Comment by pasikarkkainen** [comment]
Sorry for the confusion. For me mkchromecast was installed using these instructions: https://github.com/muammar/mkchromecast/wiki/macOS-standalone-app . So basicly sources cloned from github, and the rest of the components (python3, git, qt5, etc) installed with brew. I just ran "python3 mkchromecast.py -v" and it confirms it's v0.3.7.

And my chromecast devices have different names ("chromecastultra-foo1" and "chromecastaudio-foo1").

**Comment by muammar** [comment]
Thank you @sabret00the and @pasikarkkainen for posting your messages. I will investigate more in details to fix this problem.

**Comment by pasikarkkainen** [comment]
@muammar : Thanks for looking into this. Let me know if you need more info, or if there's something to test/verify.

**Comment by muammar** [comment]
@pasikarkkainen I have pushed https://github.com/muammar/mkchromecast/commit/b8927f176caa18065da8815be07db1e63d69786d. Can you let me know if this is working for you?.

**Comment by pasikarkkainen** [comment]
@muammar now it seems better! I'm actually able to choose the correct chromecast device.. and only one device gets chosen, just like it should be. Thanks a lot!

**Comment by muammar** [comment]
@pasikarkkainen thanks for confirming that is working now :). I will wait some more for @sabret00the to close this report.

**Comment by muammar** [comment]
I am proceeding to close this report. If you consider that the issue is not solved, please feel free to re-open it again. Thanks.

**Comment by Vednier** [comment]
Well, i kinda late to barge in into this bug, but there is still minor leftovers of problem present, imho.
I have two chromecasts, one Chromecast 2013 and Chromecast audio. Previously, on mkchromecast 0.3.6 on Ubuntu 16.10 there was problem with inability to select Audio chromecast when 2013 one is online (it was always selected instead Audio). On 0.3.7 this problem is gone. But...for some reason when i select one of chromecasts both getting marked as connected when actually only one is. Not like critical, but confusing.

**Comment by pasikarkkainen** [comment]
@Vednier : "both get selected" was already fixed, see discussion above. mkchromecast v0.3.7 is not enough, you need the latest git master version to get the bugfix.

**Comment by muammar** [comment]
@pasikarkkainen thanks for the clarification. I uploaded a new version to Debian archives, so in anytime will be synced to ubuntu repos @Vednier.

**Comment by xmbwd** [comment]
I used the latest file from the [Debian packages](https://packages.debian.org/stretch/mkchromecast), `mkchromecast_0.3.7+git20170130-2_all.deb`, and the "both get selected" bug remains for me.  I understood from the last comment by @muammar that this was the latest version.  If so, the bug remains. If not, please let me know where to find the latest.

**Comment by muammar** [comment]
@xmbwd  Try the one in unstable https://packages.debian.org/unstable/mkchromecast.

**Comment by xmbwd** [comment]
Yep.  That fixed it.

**Comment by muammar** [comment]
@xmbwd can you open a new report with this, please?. Thanks for noticing this problem. It may be easy to fix.
